package com.cjq.common;

public enum FieldFunction {
    COUNT, MAX, MIN, AVG, SUM, CONCAT, SUBSTRING, LENGTH, UPPER, LOWER, TRIM, REPLACE, ABS, CEIL, FLOOR, ROUND,
    TRUNCATE, MOD, POW, SQRT, RAND, NOW, CURDATE, CURTIME, DATE_FORMAT, DATEDIFF, DAY, MONTH,YEAR, HOUR, MINUTE,
    IF,IFNULL, COALESCE, CASE_WHEN, CAST
}
