package com.cjq.common;

public enum OperatorSymbol {
    EQ, GT, LT, GTE, LTE, N, IS, ISN, LIKE, NLIKE, NIN, IN, BETWEEN, NBETWEEN, GEO_INTERSECTS, GEO_BOUNDING_BOX, REGEXP,
    GEO_DISTANCE, GEO_POLYGON, NESTED_COMPLEX, NNESTED_COMPLEX, CHILDREN_COMPLEX, SCRIPT, MATCH, MATCH_PHRASE, TERM
}
